### ISSUE TITLE
Group Playbook Task results ... per task

### ISSUE THREAD

**Issue by stdedos** [ansible-community/ara-web#7] opened 2019-05-13 12:51 UTC
As a user, I would expect to have a more consise output like:

Task Name | Action | Elasped | Duration | Status
-- | -- | -- | -- | --
Task 1 | x | AVG 0s | AVG 1s | 11 / OK
Task 2 | y | AVG 1m | AVG 1m | 11 / CHANGED
Task 3 | z | AVG 1.5m | AVG 1.5m | 10 / CHANGED, 1 FAILED
Task 4 | a | AVG 0s | AVG 1s | 11 / SKIPPED

which could then, expand and/or track per host what has happened

e.g. 10 hosts * 28 tasks is not fun to go through

**Comment by dmsimard** [comment] 2019-05-15 14:14
The transfer worked \o/

We have not settled on the actual layout of the reports in the new UI yet, mostly focusing on making sure that the new API provides the necessary information in the right format and that querying the API works.

I'll leave this opened.

**Comment by guillaumevincent** [comment] 2019-05-17 12:20
Regrouping the status per task is a really good idea

**Comment by guillaumevincent** [comment] 2019-05-22 12:23
This will be fixed after https://review.opendev.org/660698 merged

**Comment by stdedos** [comment] 2019-05-22 12:48
> This will be fixed after https://review.opendev.org/660698 merged

Perfect. Please give me instructions so I can update my playground too!

> Example: http://logs.openstack.org/98/660698/1/check/ara-web-build-dashboard/503764e/npm/html/playbooks/1

"File not found" as of now

**Comment by dmsimard** [comment] 2019-05-22 13:38
@stdedos @guillaumevincent the link is broken because of the routing -- try this instead (no /playbooks/1): http://logs.openstack.org/98/660698/1/check/ara-web-build-dashboard/503764e/npm/html

**Comment by stdedos** [comment] 2019-05-22 13:56
I am not sure what am I seening now to be honest.

Could the testcase be extended to have 2 hosts, and preferably "fabricate" one of the hosts, so that it acts differently on some tasks?

**Comment by dmsimard** [comment] 2019-05-22 15:38
Yes, actually there ought to be more results in that demo -- there is a regression with Ansible 2.8 that I'm working to fix right now: https://github.com/ansible-community/ara/issues/46

Meanwhile, I've updated the API demo with a database after the fix which contains more things so you can have another look.

Here's a screenshot
![list](https://user-images.githubusercontent.com/1291204/58188032-f0906400-7c85-11e9-8b0b-d8807d0656a3.png)

And another:
![details](https://user-images.githubusercontent.com/1291204/58188065-fd14bc80-7c85-11e9-9894-a6d8d23731e3.png)

**Comment by guillaumevincent** [comment] 2019-05-22 16:00
This is a work in progress, I will update the duration to make them more human readable

**Closed** 2019-05-22 16:31 UTC
Labels: enhancement, help wanted

**Comment by dmsimard** [comment] 2019-05-22 17:29
@stdedos 

> Perfect. Please give me instructions so I can update my playground too when this is merged!

The change is merged so you can just pull the latest code from https://github.com/ansible-community/ara-web and re-install that.

**Comment by stdedos** [comment] 2019-05-22 17:33
I was wondering about that; I think I have installed "one package", and not separate packages. 

Should "the new packages" be an in-place replacement for the "one" package?

**Comment by dmsimard** [comment] 2019-05-22 17:37
@stdedos From source, running ``npm install`` will install (or update) the dependencies and put them in a ``node_modules`` folder in the current working directory.
``npm start`` will start the embedded server using those dependencies.

Otherwise there is a role which basically takes care of this for you: https://ara.readthedocs.io/en/feature-1.0/ansible-role-ara-web.html

Documentation for ara-web is a bit light right now, happy to accept patches :)

**Comment by stdedos** [comment] 2019-05-23 06:26
Now I remember more; I used `pip install ara # ara==2.7.8` to make everything work.

So, now the `ara-web` is coming from `npm`, and the rest "as usual"?

**Comment by dmsimard** [comment] 2019-05-23 20:04
@stdedos yes, ara-web is a standalone web client that provides an interface to the new API in ara.
There are docs on how to get started with ARA 1.0 ahead of release here: https://ara.readthedocs.io/en/feature-1.0/installation.html

**Comment by guillaumevincent** [comment] 2019-05-23 20:48
@stdedos just to be clear `ara-web` is not on npm, `ara-web` can be installed from source using `npm` or `yarn`

**Comment by dmsimard** [comment] 2019-05-24 15:26
@stdedos This new UI is a client interface to a yet-unreleased version of ARA, 1.0.
ARA 0.x doesn't provide an API and comes with it's own bundled web interface.

You can install the beta pre-release by using ``pip install --pre ara`` instead of ``pip install ara``.
If you have any questions, feel free to hop on [IRC or Slack](https://ara.recordsansible.org/community/)
